run_analysis <- function(){
     #Load in the data files
     #First, I load in the Features, or the variables for the main data
     features <- read.delim(file="./features.txt",header=F,
                            sep=" ")
     #then I load in the Test Subject information
     TestSubject <- read.delim(file="./subject_test.txt",
                               header=F)
     
     #then rename the variable for clarity.
     names(TestSubject)[1] <- "SubjectID"
     
     #Load the activity information, numbered 1-6
     TestActivity <- read.delim(file="./y_test.txt", 
                                header=F)
     
     #As with the SubjectID, I rename the Activity variable for clarity
     names(TestActivity)[1] <- "ActivityID"
     
     #Load to the main test data
     TestData <- read.table(file="./X_test.txt",header=F)
     
     #Rename the variables in the test data from default V1, V2, etc
     #to reflect the Features data we read in above.
     colnames(TestData) <- features$V2
     
     #Merge the Test Subject, Test Activity and Test Data together.
     fullTestData <- cbind(TestSubject,TestActivity,TestData)
     
     #Still loading data files, this time the TRAIN Subject
     TrainSubject <- read.delim(file="./subject_train.txt",
                                header=F)
     
     #Rename the variable for clarity
     names(TrainSubject)[1] <- "SubjectID"
     
     #Load the Activity information, again numbered 1-6
     TrainActivity <- read.delim(file="./y_train.txt", 
                                 header=F)
     
     #Rename the variable for clarity
     names(TrainActivity)[1] <- "ActivityID"
     
     #Load main Training Data file
     TrainData <- read.table(file="./X_train.txt",
                             header=F)
     
     #Rename the variables from default V1, V2, etc. to the Features list
     colnames(TrainData) <- features$V2
     
     #Merge the Subject, Activity & Training Data sets together.
     fullTrainData <- cbind(TrainSubject,TrainActivity,TrainData)
     
     #Merge the Test Data with the Train Data
     fullData <- rbind(fullTestData,fullTrainData)
     
     
     #Use logical-boolean regular expression to identify variables in the
     #full data set to keep. In this case, any variables identifying MEAN() or
     #STD() information, as well as retaining my main Subject and Activity 
     #identifier variables.
     varMeanSTD <- grepl('mean\\(\\)',colnames(fullData)) | grepl('std\\(\\)',
                    colnames(fullData)) | grepl('SubjectID',colnames(fullData))|
                    grepl('ActivityID',colnames(fullData))
     
     #Subset to keep only desired variables
     cleanData <- fullData[,varMeanSTD]
     
     #Clean up the variable names a bit more to remove unsightly brackets, clean
     #duplication of "Body" in some variable names - fBodyBodyAccJerkMag-std
     colnames(cleanData) <- gsub("\\(\\)","",colnames(cleanData))
     colnames(cleanData) <- gsub("BodyBody","Body",colnames(cleanData))
     
     
     #Read in the activity list, the labels associated with the numerical
     #activityID
     activitySet <- read.delim(file="./activity_labels.txt",
                               header=F, sep=" ",
                               col.names = c("ActivityID","ActivityLabel"))
     
     #Left merge to add Activity Labels to the main data, matching by ActivityID
     cleanData <- merge(cleanData,activitySet,by="ActivityID",all.x=T)
     #Overwrite the numerical values with their labels
     cleanData$ActivityID <- as.character(cleanData$ActivityID)
     cleanData$ActivityID <- cleanData$ActivityLabel
     #Delete the unneeded Label variable
     cleanData$ActivityLabel <- NULL
     
     #Now we melt the data into a long data set
     cdl <- melt(cleanData,id.vars = c("SubjectID","ActivityID"))
     
     #Take the long data and reshape it, aggregating the MEAN value of the 
     #variable (generated by the melt) by Subject and Activity.
     #THIS IS THE TIDY DATA SET.
     cdld <- dcast(cdl,SubjectID + ActivityID ~ variable,mean)
     
     #Write the tidy data to a file.
     write.table(cdld,file = "./Assignment Step 5.txt",row.names = F)
     
}